spring:
  datasource:
    hikari:
      driver-class-name: 'net.sf.log4jdbc.sql.jdbcapi.DriverSpy'
      jdbc-url: jdbc:log4jdbc:mariadb://jdu.iptime.org:23306/recreation?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: admin
      password: Thfk#930828

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  devtools:
    livereload:
      enabled: true

  # 로깅 설정
  logging:
    level:
      com:
        apprentice: DEBUG
      org:
        springframework: INFO
        thymeleaf: DEBUG
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE

  # 메시지 관리 설정(오류메시지 등)
  messages:
    basename: messages, ValidationMessages, PropertyNames
    cache-duration: -1
    encoding: UTF-8